### ISSUE TITLE
Crash on loading modpack

### ISSUE THREAD

**Issue by pupnewfster** [daedalus4096/Thaumic-Brewing#1]
https://paste.dimdev.org/jefovihisa.mccrash
Thaumic Brewing version: 1.0.0
Forge: 14.23.5.2808

**Comment by daedalus4096** [comment]
I'm unable to replicate this issue in my dev environment with Forge 2808, which leads me to suspect that this is somehow caused by a conflict with another mod.  What's the name and version of the modpack that you're using?  Perhaps I can recreate it with that.

**Comment by daedalus4096** [comment]
On second look, it seems that the Forge version might be the problem itself.  I developed on 2768, and have now updated the mod to 2808.  Please try version 1.0.1 of the mod once it's approved for download.

**Comment by pupnewfster** [comment]
Actually it is a pack I haven't released yet. But I am getting the same crash with just Baubles, Thaumcraft, and Thaumic Brewing.
I also tried going against forge 2768 to see if that would make it work. But given it is saying that Items.POTIONITEM could not be found that seems to me like you may not be reobfuscating when compiling. Or at least that is my theory for what may be wrong.

**Comment by daedalus4096** [comment]
Please let me know if 1.0.1 doesn't work for you.  I'm still very new to modding, so I appreciate your insight.

**Comment by pupnewfster** [comment]
It still doesn't work but when I downloaded the source. Ran `setupDecompWorkspace` and then `build` it works properly.
I would also make sure to run `clean` before `build` or just run `clean build`. When I look at your jar file you have a `com/examples` folder so I think you have have some stuff that is improperly cached.

Also if you want you can update the mappings in your build.gradle to `stable_39` as that is the final mappings for MinecraftForge 1.12 rather than using ones from 2017. (If you do this make sure to run the `setupDecompWorkspace` again afterwards)
